- name: Deploy custom 
  hosts: nginx_servers
  become: true
  vars:
     site_name: "DevOps Training Site"

  tasks:
    - name: Copy index 
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

