apiVersion: v1
kind: Pod
metadata:
  name: busybox-hdd
  labels:
    app: busybox-logger
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo logging agent; sleep 3600; done"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd
