apiVersion: v1
kind: Pod
metadata:
  name: nginx-ssd
  labels:
    app: nginx-ssd
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
  nodeSelector:
    disktype: ssd