---
- name: Install Docker and run NGINX container
  hosts: DockerHost
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run NGINX container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"

    - name: Show running containers (docker ps)
      shell: docker ps
      register: docker_ps_output

    - name: Display docker ps output
      debug:
        msg: "{{ docker_ps_output.stdout }}"
